name = "Better Building"
author = "o4bit"
version = "8.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21d8980f36b9b3ee7d9c48be013fae09948b93059912934e9badee37a4035c93"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
