name = "Better Building"
author = "o4bit"
version = "6.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aac57e5e65074f01b043de939ccf64cf9f250ac052986ed91386edc19a1147f8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
